ARG JAVA_RUNTIME_IMAGE=docker.io/library/amazoncorretto:21-alpine-jdk

FROM ${JAVA_RUNTIME_IMAGE}

WORKDIR /server

RUN addgroup -S velocity \
    && adduser -S velocity -G velocity \
    && mkdir -p /opt/velocity/plugins /server/plugins \
    && chown -R velocity:velocity /opt/velocity /server

COPY --chown=velocity:velocity velocity.jar /opt/velocity/velocity.jar
COPY --chown=velocity:velocity plugins/sisr-proxy.jar /opt/velocity/plugins/sisr-proxy.jar
COPY --chown=velocity:velocity entrypoint.sh /usr/local/bin/velocity-entrypoint

RUN chmod +x /usr/local/bin/velocity-entrypoint

EXPOSE 25565/tcp
VOLUME ["/server"]

USER velocity
ENTRYPOINT ["/usr/local/bin/velocity-entrypoint"]
